# gen_sections package — Generalist thesis section renderers
from .abstract_gen import AbstractGenSection
from .appendix_gen import AppendixGenSection
from .base_gen_section import BaseGenSection
from .conclusion_gen import ConclusionGenSection
from .cost_capacity import CostCapacitySection
from .data_methodology_gen import DataMethodologyGenSection
from .discussion_gen import DiscussionGenSection
from .implications import ImplicationsSection
from .institutional_background import InstitutionalBackgroundSection
from .introduction_gen import IntroductionGenSection
from .mechanism import MechanismSection
from .references_gen import ReferencesGenSection
from .related_literature import RelatedLiteratureSection
from .results_analysis import ResultsAnalysisSection
from .risk_adjusted_results import RiskAdjustedResultsSection
from .robustness_gen import RobustnessGenSection
from .stylized_facts import StylizedFactsSection
from .theoretical_framework import TheoreticalFrameworkSection
from .title_page_gen import TitlePageGenSection
