"""Strategy catalog — the shared 'catalog/INDEX.md'.

A quick "what strategies do we have" overview, auto-built from each strategy's
``config.json`` (name/category/status) + its ``artifacts/<slug>_summary.json``
(metrics + validation verdict). Regenerated by ``rigor index`` and on every
``rigor run``, committed so every clone sees it on pull. Deterministic (sorted,
no wall-clock) so it only changes when a strategy's numbers/status change.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..data.config import find_repo_root
from . import layout

_STATUS_ORDER = {"live": 0, "paper": 1, "idle": 2}


def _f2(x) -> str:
    return f"{x:.2f}" if isinstance(x, (int, float)) else "—"


def _pct(x) -> str:
    return f"{x * 100:.1f}%" if isinstance(x, (int, float)) else "—"


def collect(root: Path) -> list[dict]:
    """Gather one row per PRODUCTION strategy from config.json + summary.json.

    Baselines (under ``strategies/Baseline/``) are deliberately excluded — the
    catalog lists deployable/working strategies only.
    """
    rows: list[dict] = []
    sroot = layout.strategies_root(root)
    if not sroot.is_dir():
        return rows
    for cfg_file in sorted(sroot.rglob("config.json")):
        if layout.is_baseline_rel(cfg_file.parent.relative_to(sroot)):
            continue  # baselines are not part of the shared catalog
        d = cfg_file.parent
        try:
            raw = json.loads(cfg_file.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        slug = raw.get("slug", d.name)
        summ_file = d / layout.ARTIFACTS_DIR / f"{slug}_summary.json"
        summ: dict = {}
        if summ_file.exists():
            try:
                summ = json.loads(summ_file.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                summ = {}
        m, v = summ.get("metrics", {}), summ.get("verdict", {})
        rows.append({
            "name": raw.get("name", slug),
            "category": raw.get("category", d.parent.name),
            "status": raw.get("status", "idle"),
            "version": raw.get("version", "v1"),
            "sharpe": m.get("sharpe"),
            "cagr": m.get("cagr"),
            "maxdd": m.get("max_drawdown"),
            "n": m.get("n_obs"),
            "verdict": v.get("verdict"),
            "score": v.get("score"),
            "as_of": summ.get("as_of"),
        })
    return rows


def render(rows: list[dict]) -> str:
    rows = sorted(rows, key=lambda r: (r["category"], r["name"].lower()))
    cols = ["Strategy", "Category", "Status", "Ver", "Sharpe", "CAGR", "Max DD",
            "Verdict", "n", "Data as-of"]
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join(["---"] * len(cols)) + "|"]
    for r in rows:
        verdict = f"{r['verdict']} ({r['score']})" if r.get("verdict") else "— not run"
        lines.append("| " + " | ".join([
            r["name"], r["category"], r["status"], r.get("version", "v1"),
            _f2(r["sharpe"]), _pct(r["cagr"]), _pct(r["maxdd"]),
            verdict, str(r["n"] or "—"), r.get("as_of") or "—",
        ]) + " |")

    by_status: dict[str, list[str]] = {}
    for r in rows:
        by_status.setdefault(r["status"], []).append(r["name"])
    status_lines = [
        f"- **{s}** ({len(by_status[s])}): " + ", ".join(sorted(by_status[s]))
        for s in sorted(by_status, key=lambda x: _STATUS_ORDER.get(x, 9))
    ]

    return (
        "# Strategy catalog\n\n"
        "_Auto-generated by `rigor index` (and on every `rigor run`). Do not edit by hand._\n"
        "_Production strategies only; raw baselines under `strategies/Baseline/` are excluded._\n\n"
        f"**{len(rows)} strategies.**\n\n"
        "## Catalog\n\n" + "\n".join(lines) + "\n\n"
        "## By status\n\n" + ("\n".join(status_lines) if status_lines else "_none_") + "\n"
    )


def write_index(root: Path | None = None) -> Path:
    """Regenerate the catalog at ``<root>/catalog/INDEX.md``."""
    root = Path(root) if root else find_repo_root()
    out = layout.index_path(root)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(collect(root)), encoding="utf-8")
    return out
